name=Criatronix LAB library
version=1.0.0
author=Pedro Campanari
maintainer=CLAB <info.criatronixlab.lib@google.com>
sentence=Arduino library for CLAB board
paragraph=Arduino library for CLAB board
category=Sensors and Board
url=https://github.com/pedrocampanari/criatronixLAB_lib
architectures=avr
depends=Servo, dht